import type {Metadata} from 'next';
import './index.css';
import {ReactNode} from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-100 overscroll-none">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="canonical" href="https://www.shuoink.com" />
        <title>shuoink.com</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
